name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      # 拉取代码
      - uses: actions/checkout@v4
      # 安装依赖
      - name: Install dependencies
        run: pip install beautifulsoup4
      # 补全网页内容
      - name: Run Makefile
        run: make all
      # 部署网页
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}